import type { Verb } from "./types";

export const translatedVerbs = [
  "aceptar",
  "comprar",
  "añadir",
  "admirar",
  "admitir",
  "ofrecerse",
  "estar de acuerdo",
  "autorizar",
  "responder",
  "disculpar(se)",
  "aparecer",
  "preguntar",
  "evitar",
  "ser, estar",
  "vencer",
  "volverse",
  "comenzar",
  "comportarse",
  "creer",
  "pertenecer",
  "doblar",
  "apostar",
  "bloquear",
  "reservar",
  "pedir prestado",
  "romper",
  "llevar",
  "traer",
  "emitir, transmitir",
  "construir",
  "quemar",
  "llamar",
  "anular, cancelar",
  "capturar, atrapar",
  "cambiar",
  "verificar",
  "elegir",
  "venir",
  "regresar",
  "preocupar",
  "confirmar",
  "considerar",
  "contactar",
  "continuar",
  "convencer",
  "cocinar",
  "copiar",
  "corregir",
  "costar",
  "cubrir",
  "crear",
  "cortar",
  "bailar",
  "decidir",
  "retrasar",
  "entregar",
  "morir",
  "decepcionar",
  "hacer, fabricar",
  "dudar",
  "ganar (dinero)",
  "esperar",
  "caer",
  "temer",
  "sentir",
  "encontrar",
  "volar",
  "seguir",
  "prohibir",
  "predecir",
  "olvidar",
  "perdonar",
  "congelar",
  "recoger",
  "obtener",
  "dar",
  "devolver",
  "ir",
  "crecer",
  "ocurrir",
  "odiar",
  "tener",
  "oír",
  "ayudar",
  "resaltar",
  "llegar, alcanzar",
  "sostener",
  "tener esperanza",
  "herir, dañar",
  "ignorar",
  "implementar",
  "impresionar",
  "incluir",
  "tener la intención de",
  "implicar",
  "planchar",
  "guardar, mantener",
  "matar",
  "besar",
  "saber",
  "guiar",
  "aprender",
  "irse, partir",
  "dejar",
  "iluminar",
  "vivir",
  "cargar",
  "mirar",
  "perder",
  "querer decir",
  "conocer",
  "mover",
  "necesitar",
  "ofrecer",
  "abrir",
  "superar",
  "pasar, aprobar",
  "pegar",
  "pagar",
  "jugar",
  "prometer",
  "suministrar",
  "empujar",
  "aumentar",
  "leer",
  "recordar",
  "informar",
  "recompensar",
  "sonar",
  "levantar",
  "correr",
  "decir",
  "ver",
  "parecer",
  "vender",
  "enviar",
  "servir",
  "poner",
  "agitar",
  "mostrar",
  "sentarse",
  "hablar",
  "gastar",
  "escupir",
  "desperdiciar",
  "esparcir",
  "ponerse de pie",
  "quedarse",
  "apestar",
  "parar",
  "golpear",
  "esforzarse",
  "estudiar",
  "triunfar",
  "sufrir",
  "sugerir",
  "soportar, apoyar",
  "sobrevivir",
  "jurar",
  "sudar",
  "barrer",
  "nadar",
  "tomar",
  "enseñar",
  "llorar",
  "agradecer",
  "pensar",
  "tirar",
  "confiar",
  "intentar",
  "girar",
  "entender",
  "utilizar",
  "caminar",
  "querer",
  "lavar",
  "humedecer",
  "ganar",
  "retirar",
  "presenciar",
  "trabajar",
  "escribir",
]

export const verbs: Verb[] = [
  {
    value: "accept",
    translations: [
      "aceptar",
      "admitir"
    ],
    examplePhrases: [
      "I accept your apology and hold no grudges against you.",
      "The university will accept applications until the end of the month.",
      "Despite their differences, they learned to accept each other's perspectives and live in harmony."
    ]
  },
  {
    value: "acquire",
    translations: [
      "comprar",
      "adquirir",
      "obtener"
    ],
    examplePhrases: [
      "He aims to acquire a new skill every month to broaden his expertise.",
      "The company plans to acquire a smaller startup to expand its market reach.",
      "Through hard work and dedication, she was able to acquire a vast collection of rare books."
    ]
  },
  {
    value: "add",
    translations: [
      "añadir",
      "agregar",
      "sumar"
    ],
    examplePhrases: [
      "Please add sugar to your coffee if you prefer it sweet.",
      "Let's add some spice to this recipe to give it more flavor.",
      "Don't forget to add your signature at the bottom of the document."
    ]
  }
]