import GuessTheVerbMode from "@/components/GuessTheVerbMode";
import Title from "@/components/Title";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Guess the Verb 🔮 • Guess English",
  description: "Generated by create next app",
};

export default function GuessTheVerbPage() {
  return (
    <main className="px-6 container mx-auto grid grid-rows-10 max-h-screen min-h-screen">
      <header className="row-span-2 flex flex-col gap-y-8 items-center justify-center">
        <Title>
          ¡Guess <br className="md:hidden" /> the verb!
        </Title>
      </header>
      <section className="relative row-span-6">
        <GuessTheVerbMode />
      </section>
      <footer className="row-span-2">

      </footer>
    </main>
  )
}
