import GoBackButton from "@/components/GoBackButton";
import Title from "@/components/Title";
import VerbsHistory from "@/components/VerbsHistory";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Verbs History 🔮 • Guess English",
  description: "Generated by create next app",
};

export default function VerbsHistoryPage() {
  return (
    <main className="px-6 container mx-auto grid grid-rows-10 max-h-screen min-h-screen">
      <header className="row-span-2 flex flex-col gap-y-8 items-center justify-center">
        <div className="w-full grid grid-cols-3">
          <GoBackButton backTo="home" label="Back to home" />
        </div>
        <Title>
          Verbs <br className="md:hidden" /> History
        </Title>
      </header>
      <section className="relative row-span-6">
        <VerbsHistory />
      </section>
      <footer className="row-span-2">

      </footer>
    </main>
  )
}
