import GoBackButton from "@/components/GoBackButton";
import { Smoke4 } from "@/components/Smokes";
import Title from "@/components/Title";
import VerbsHistory from "@/components/guess-the-verb/VerbsHistory";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Verbs History 🔮 • Guess English",
  description: "Generated by create next app",
};

export default function VerbsHistoryPage() {
  return (
    <>
      <Smoke4 />
      <main className="container flex flex-col min-h-screen px-6 mx-auto">
        <header className="flex flex-col items-center justify-center my-5 min-h-60 gap-y-8">
          <div className="grid w-full grid-cols-3">
            <GoBackButton backTo="home" label="Back to home" />
          </div>
          <Title>
            Verbs <br className="md:hidden" /> History
          </Title>
        </header>
        <section className="relative my-5 min-h-96">
          <VerbsHistory />
        </section>
      </main>
    </>
  )
}
