import GoBackButton from "@/components/GoBackButton";
import { Smoke4 } from "@/components/Smokes";
import Title from "@/components/Title";
import DialoguesMode from "@/components/dialogues/DialoguesMode";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Dialogues 🔮 • Guess English",
  description: "Generated by create next app",
};

export default function DialoguesPage() {
  return (
    <>
      <Smoke4 />
      <main className="container grid max-h-screen min-h-screen px-6 mx-auto grid-rows-10">
        <header className="flex flex-col items-center justify-center row-span-2 gap-y-8">
          <div className="grid w-full grid-cols-3">
            <GoBackButton backTo="home" label="Back to home" />
          </div>
          <Title>
            Dialogues
          </Title>
        </header>
        <section className="relative row-span-6">
          <DialoguesMode />
        </section>
      </main>
    </>
  )
}